### ISSUE TITLE
KeyError: 'objects'

### ISSUE THREAD

**Issue by waseltzer** [iMicknl/ha-nest-protect#102]
### The problem

2022-09-29 23:21:57.036 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 152, in _async_subscribe_for_data
    for bucket in result["objects"]:
KeyError: 'objects'

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.9.7

### Device / Model

Nest Protect / Topaz-2.5, Nest Temperature Sensor / KR1

### Diagnostics information
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Denver",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.09.1",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "nest_protect": {
      "version": "0.3.8",
      "requirements": []
    },
    "keymaster": {
      "version": "v0.0.82",
      "requirements": []
    },
    "google_home": {
      "version": "1.9.15",
      "requirements": [
        "glocaltokens==0.6.8"
      ]
    },
    "bhyve": {
      "version": "3.0.0",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    },
    "alexa_media": {
      "version": "4.1.2",
      "requirements": [
        "alexapy==1.26.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "rpi_gpio": {
      "version": "2022.7.0",
      "requirements": [
        "RPi.GPIO==0.7.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "config_flow": true,
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "codeowners": [
      "@imicknl"
    ],
    "iot_class": "cloud_polling",
    "version": "0.3.8",
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "is_built_in": false
  },
  "data": {
    "app_launch": {
      "updated_buckets": [
        {
          "object_key": "kryptonite.18B430C6E35730C1",
          "object_revision": 20723,
          "object_timestamp": 1664511519707,
          "value": {
            "model": "KR1",
            "description": "Bedroom",
            "last_updated_at": 1664511519,
            "structure_id": "1888eed0-596e-11e5-b6ab-22000b6d823e",
            "current_temperature": 24.09999,
            "where_id": "00000000-0000-0000-0000-00010000000f",
            "serial_number": "**REDACTED**",
            "battery_level": 100
          }
        },
        {
          "object_key": "topaz.18B43000002F7150",
          "object_revision": 14482,
          "object_timestamp": 1664515491444,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-00010000000f",
            "creation_time": 1448066034000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.123.198",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A2",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "C06044378EDEF8D9",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "description": "Upstairs top of stairs",
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1662838780,
            "home_away_input": true,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.1",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 16384,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1758067200,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1662838777,
            "component_pir_test_passed": true,
            "structure_id": "1888eed0-596e-11e5-b6ab-22000b6d823e",
            "software_version": "3.4.1rc1",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1534174016,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1534173993,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-00010000000f",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 16384,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1442448000,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5246
          }
        },
        {
          "object_key": "topaz.18B43000002B2D64",
          "object_revision": 24290,
          "object_timestamp": 1664515620691,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-000100000002",
            "creation_time": 1448065735000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.123.188",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A2",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "C06044378EDEF8D9",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1662838783,
            "home_away_input": true,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.16",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 16384,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1750896000,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1662838780,
            "component_pir_test_passed": true,
            "structure_id": "1888eed0-596e-11e5-b6ab-22000b6d823e",
            "software_version": "3.4.1rc1",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1534174016,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1534173993,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 2,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "5cab3e80-d08e-49cf-849a-69ced9e47016",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 16384,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1435276800,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5282
          }
        },
        {
          "object_key": "where.1888eed0-596e-11e5-b6ab-22000b6d823e",
          "object_revision": -21973,
          "object_timestamp": 1565708226898,
          "value": {
            "wheres": [
              {
                "where_id": "5cab3e80-d08e-49cf-849a-69ced9e47016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000000",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000001",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000002",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000003",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000004",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000005",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000006",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000007",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000009",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000e",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000f",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000010",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000011",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000012",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000013",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000014",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000015",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000017",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000018",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001d",
                "name": "**REDACTED**"
              }
            ]
          }
        },
        {
          "object_key": "topaz.18B4300000316FEB",
          "object_revision": 1026,
          "object_timestamp": 1664515667002,
          "value": {
            "spoken_where_id": "00000000-0000-0000-0000-000100000001",
            "creation_time": 1458230716000,
            "installed_locale": "en_US",
            "ntp_green_led_brightness": 3,
            "component_buzzer_test_passed": true,
            "wifi_ip_address": "192.168.123.209",
            "wired_led_enable": true,
            "wifi_regulatory_domain": "A2",
            "co_blame_duration": 0,
            "is_rcs_capable": false,
            "fabric_id": "C06044378EDEF8D9",
            "battery_health_state": 0,
            "steam_detection_enable": true,
            "hushed_state": false,
            "capability_level": 2.0,
            "home_alarm_link_type": 0,
            "model": "Topaz-2.7",
            "component_smoke_test_passed": true,
            "component_speaker_test_passed": true,
            "removed_from_base": false,
            "smoke_sequence_number": 0,
            "last_audio_self_test_end_utc_secs": 1662838784,
            "home_away_input": true,
            "device_locale": "en_US",
            "co_blame_threshold": 0,
            "kl_software_version": "3.0.2",
            "component_us_test_passed": false,
            "auto_away": true,
            "night_light_enable": true,
            "component_als_test_passed": true,
            "speaker_test_results": 16384,
            "wired_or_battery": 0,
            "is_rcs_used": false,
            "replace_by_date_utc_secs": 1763337600,
            "certification_body": 1,
            "last_audio_self_test_start_utc_secs": 1662838782,
            "component_pir_test_passed": true,
            "structure_id": "1888eed0-596e-11e5-b6ab-22000b6d823e",
            "software_version": "3.4.1rc1",
            "component_hum_test_passed": true,
            "home_alarm_link_capable": false,
            "night_light_brightness": 3,
            "device_external_color": "white",
            "latest_manual_test_end_utc_secs": 1534174024,
            "smoke_status": 0,
            "latest_manual_test_start_utc_secs": 1534173963,
            "component_temp_test_passed": true,
            "home_alarm_link_connected": false,
            "co_status": 0,
            "heat_status": 0,
            "product_id": 9,
            "night_light_continuous": false,
            "co_previous_peak": 0,
            "auto_away_decision_time_secs": 600,
            "component_co_test_passed": true,
            "where_id": "00000000-0000-0000-0000-000100000001",
            "serial_number": "**REDACTED**",
            "component_heat_test_passed": false,
            "latest_manual_test_cancelled": false,
            "thread_mac_address": "**REDACTED**",
            "resource_id": "topaz_resource.5",
            "buzzer_test_results": 16384,
            "wifi_mac_address": "**REDACTED**",
            "line_power_present": true,
            "gesture_hush_enable": false,
            "device_born_on_date_utc_secs": 1447718400,
            "ntp_green_led_enable": true,
            "component_led_test_passed": true,
            "co_sequence_number": 0,
            "thread_ip_address": "**REDACTED**",
            "component_wifi_test_passed": true,
            "heads_up_enable": true,
            "battery_level": 5254
          }
        },
        {
          "object_key": "structure.1888eed0-596e-11e5-b6ab-22000b6d823e",
          "object_revision": -26591,
          "object_timestamp": 1664514374080,
          "value": {
            "swarm": [
              "kryptonite.18B430C82A29444F",
              "topaz.18B43000002F7150",
              "kryptonite.18B430C6E35730C1",
              "topaz.18B43000002B2D64",
              "topaz.18B4300000316FEB"
            ],
            "last_action_by": "PHX",
            "manual_away_timestamp": 1664420604,
            "last_action": "RTS_SYNC",
            "emergency_contact_phone": "**REDACTED**",
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "city": "**REDACTED**",
            "name": "**REDACTED**",
            "eta_preconditioning_active": false,
            "creation_time": 1442076509784,
            "location": "**REDACTED**",
            "touched_by": {
              "touched_by": 3,
              "touched_id": "Life360",
              "touched_user_id": "client.ed6e4521-7409-49b1-a237-02d551476974"
            },
            "latitude": "**REDACTED**",
            "ifj_primary_fabric_id": "**REDACTED**",
            "state": "**REDACTED**",
            "away_timestamp": 1664420607,
            "eta_unique_id": "Leaf for Pebbleleaf-eta_copy_of_active_trip",
            "structure_area": 3000.0,
            "topaz_hush_key": "**REDACTED**",
            "enable_goose": false,
            "away_setter": 1,
            "phone_hush_enable": true,
            "hvac_safety_shutoff_enabled": true,
            "house_type": "family",
            "demand_charge_enabled": true,
            "rcs_sensor_swarm": [
              "kryptonite.18B430C82A29444F",
              "kryptonite.18B430C6E35730C1"
            ],
            "eta_last_active_unique_id": "Google Now101201571730607719135-2016-06-23_copy_of_active_trip",
            "longitude": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "topaz_enhanced_auto_away_enabled": true,
            "address_lines": "**REDACTED**",
            "country_code": "US",
            "hvac_smoke_safety_shutoff_enabled": true,
            "topaz_away": false,
            "tou_enabled": true,
            "renovation_date": "1980",
            "vacation_mode": false,
            "fabric_ids": [
              "C06044378EDEF8D9"
            ],
            "eta": 1502282405,
            "postal_code": "**REDACTED**",
            "num_thermostats": "1",
            "entitlements": {},
            "dr_reminder_enabled": true,
            "members": [
              {
                "user": "**REDACTED**",
                "roles": [
                  "member"
                ]
              },
              {
                "user": "**REDACTED**",
                "roles": [
                  "owner"
                ]
              }
            ],
            "manual_eco_all": false,
            "emergency_contact_type": 3,
            "goose_sensor_events_enabled": true,
            "campaign_id": "8a228584-46b1-40e3-86b0-619dfe7f596d",
            "time_zone": "**REDACTED**",
            "user": "**REDACTED**",
            "clutches": [],
            "away": false,
            "devices": [],
            "tou_speedbump_count_remaining": 3
          }
        },
        {
          "object_key": "kryptonite.18B430C82A29444F",
          "object_revision": -9113,
          "object_timestamp": 1664510619737,
          "value": {
            "model": "KR1",
            "description": "Wayne's Office",
            "last_updated_at": 1664510619,
            "structure_id": "1888eed0-596e-11e5-b6ab-22000b6d823e",
            "current_temperature": 20.799988,
            "where_id": "00000000-0000-0000-0000-000100000001",
            "serial_number": "**REDACTED**",
            "last_relocation_timestamp": 1594389395,
            "battery_level": 78
          }
        }
      ],
      "service_urls": {
        "urls": {
          "rubyapi_url": "https://home.nest.com/",
          "czfe_url": "https://czfe20-front01-iad01.transport.home.nest.com",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "transport_url": "https://czfe20-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "direct_transport_url": "https://transport01-rts22-iad01.transport.home.nest.com:443"
        },
        "limits": {
          "thermostats_per_structure": 20,
          "structures": 5,
          "smoke_detectors_per_structure": 18,
          "smoke_detectors": 54,
          "thermostats": 60
        },
        "weave": {
          "service_config": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "access_token": "**REDACTED**"
        }
      },
      "weather_for_structures": {
        "structure.1888eed0-596e-11e5-b6ab-22000b6d823e": {
          "current": {
            "icon": "mostlysunny",
            "temp_c": "**REDACTED**",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**"
          },
          "location": "**REDACTED**"
        }
      },
      "2fa_enabled": true
    }
  }
}
```
### Home Assistant log

<details><summary>Logs</summary>
```
2022-09-29 23:21:57.036 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 152, in _async_subscribe_for_data
    for bucket in result["objects"]:
KeyError: 'objects'
```

</details>

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
