### ISSUE TITLE
Unknown pynest exception. Please create an issue on GitHub with your logfile

### ISSUE THREAD

**Issue by swests** [iMicknl/ha-nest-protect#103]
### The problem

Seen this error in my HA log:
Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.9.5

### Device / Model

Protect wired (Topaz-2.7 and Topaz-2.9), Firmware 3.4.1rc1

### Diagnostics information

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:270
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 30 September 2022 at 16:49:02 (18 occurrences)
Last logged: 30 September 2022 at 17:52:38

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 266, in subscribe_for_data
    result = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe30-front01-iad01.transport.home.nest.com/v6/subscribe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 144, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 270, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while subscribing -

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by itsadamslife** [comment]
I am receiving a similar error but it is showing "error 200" instead of 400.

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:305
Integration: Nest Protect (documentation, issues)
First occurred: 07:14:12 (1 occurrences)
Last logged: 07:14:12

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 301, in subscribe_for_data
    result = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe53-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 165, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 305, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
```

**Comment by Oshuma** [comment]
Same here with HA `v2023.3.6` (docker image `929548ebbeec`).
Using the https://github.com/nicoinch/ha-nest-protect fork (commit https://github.com/nicoinch/ha-nest-protect/commit/1e62797b9464a85001bf231b7c9e44eb6eda964c as of this comment).

Log entry:

```
2023-04-23 07:06:37.108 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 301, in subscribe_for_data
    result = await response.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 67, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe110-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 165, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 305, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing -
```

**Comment by douginoz** [comment]
This same error just popped up after installing the 2023.07.1 update.  Exact same stack as above, slightly different line numbers.  Also using the fork for the cookie method.

**Comment by ninjazx06** [comment]
Started seeing a very similar error:

**home-assistant-2024.12.1
v0.3.12**

Updated to home-assistant-2024.12.4 ==> same
Tried v0.4.0b9 ==> no errors logged but nest* entities unavailable 

Log:

2024-12-26 00:02:49.117 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 266, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 82, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1277, in json
    raise ContentTypeError(
    ...<7 lines>...
    )
aiohttp.client_exceptions.ContentTypeError: 400, message='Attempt to decode JSON with unexpected mimetype: text/plain', url='https://czfe27-front01-iad01.transport.home.nest.com/v6/subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 145, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/config/custom_components/nest_protect/pynest/client.py", line 270, in subscribe_for_data
    raise PynestException(
        f"{response.status} error while subscribing - {result}"
    )
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while subscribing -

**Comment by ninjazx06** [comment]
> Started seeing a very similar error:
> 
> **home-assistant-2024.12.1 v0.3.12**
> 
> Updated to home-assistant-2024.12.4 ==> same Tried v0.4.0b9 ==> no errors logged but nest* entities unavailable
> 
> Log:
> 
> 2024-12-26 00:02:49.117 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute. Traceback (most recent call last): File "/config/custom_components/nest_protect/pynest/client.py", line 266, in subscribe_for_data result = await response.json() ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 82, in json return await super().json(*args, loads=loads, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1277, in json raise ContentTypeError( ...<7 lines>... ) aiohttp.client_exceptions.ContentTypeError: 400, message='Attempt to decode JSON with unexpected mimetype: text/plain', url='https://czfe27-front01-iad01.transport.home.nest.com/v6/subscribe'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/config/custom_components/nest_protect/**init**.py", line 145, in _async_subscribe_for_data result = await entry_data.client.subscribe_for_data( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<4 lines>... ) ^ File "/config/custom_components/nest_protect/pynest/client.py", line 270, in subscribe_for_data raise PynestException( f"{response.status} error while subscribing - {result}" ) custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while subscribing -

Figured out the issue I was having.  User error (me).  I had inadvertently deleted the home in Google Home.  Readding the home back to the account and readding the nest devices resolved my issue.

**Comment by iMicknl** [comment]
This should have been fixed in [v0.4.0b9](https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b9)!
