### ISSUE TITLE
The smoke alarm comes on but there is no trace in the home assistant

### ISSUE THREAD

**Issue by galamarco** [iMicknl/ha-nest-protect#104]
### The problem

I received the alarm notification of a Nest Protect that has detected smoke (push notification from Nest) but there is no trace of the alarm in the logs in the home assistant.

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

2022.9.7

### Device / Model

Nest protect Topaz-2.33 (with cable power supply)

### Home Assistant log

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/nest_protect/__init__.py:202
Integration: Nest Protect (documentation, issues)
First occurred: 28 settembre 2022 11:29:47 (1 occurrences)
Last logged: 28 settembre 2022 11:29:47

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 202, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host home.nest.com:443 ssl:default [Try again]

**Comment by daxzor** [comment]
I too am experiencing this. It is the worst way the integration could fail

**Comment by iMicknl** [comment]
@daxzor happy to look at this, but in the past there was no one that could test this for me. 

Do you have the same issues as above, or does it just not show up?

**Comment by galamarco** [comment]
Months later a fire alarm happened again which I heard about from the Nest app, but there is no trace in Home Assistant.
@daxzor that's a serious problem

**Comment by geert36** [comment]
Same problem here.
Yesterday I had a smoke alarm, but no trace in Home Assistant.

**Comment by TinyShark** [comment]
Adding to this that my smoke sensors also do not update/display within home assistant. Occupancy sensors working as normal however.

**Comment by iMicknl** [comment]
As mentioned before, it helps to have a diagnostic log of the moment that the smoke sensor are triggered. And good to understand if it is still a warning or an actual trigger.

In my last (accidental) test, it did show up for me in HA, so I need more logs.

**Comment by jeffdeal** [comment]
FWIW, I had two Nest Protect smoke events (heads-up alerts that I silenced) while searing my Christmas rib roast.  Both showed in the HA logbook.  I've had my Protects set up for some time, and this is the first time I've had a smoke event and remembered to check HA.

________________________________

**Comment by Roarrk** [comment]
I just had this happen to me - smoke alarm in Nest and no event triggered in HA. It has worked in the past. No errors in any logs - just no event triggering in HA and nothing to see in state changes.

**Comment by iMicknl** [comment]
@Roarrk do you use the cookie method or older version? And same as all the others in this thread, please download your diagnostics at the time that your alarm is going off. :)

**Comment by iMicknl** [comment]
I would love to debug this, but I would need some help. Anyone willing to trigger their smoke alarm? Please download your diagnostics in HA, while your alarm is triggered.

**Comment by lordbah** [comment]
I am willing, but I think we'll have to get past issue #338  first.

```
2024-06-23 16:49:58.044 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-23 16:49:58.163 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```

**Comment by tjoll** [comment]
Let me give this issue a bump. 

Last week I've had a small cooking incident in the kitchen were the Nest app reported an emergency situation, right away. 

![Screenshot_20241029_210941_Nest](https://github.com/user-attachments/assets/316001f4-b856-442e-a51a-ccbda011142d)

Now I've checked the HA entity but it did not report the situation. 

![Screenshot_20241029_211024_Home Assistant](https://github.com/user-attachments/assets/539a2cdf-cf07-4a68-a89b-63eff461c768)

The other sensors like battery status are updating fine. But the smoke or CO detection is having issues.

I'm also willing to do some testing if necessary.

HA: 2024.10.2
Protect: 0.4.0b7
Auth: cookie

**Comment by lordbah** [comment]
Tested with v0.4.0 and HA 2025.2.5 and it worked. The Smoke Status entity for the correct Nest Protect device changed to detected, and the automation triggering on that entity did trigger.

**Comment by tjoll** [comment]
> Let me give this issue a bump.
> 
> Last week I've had a small cooking incident in the kitchen were the Nest app reported an emergency situation, right away.
> 
> ![Screenshot_20241029_210941_Nest](https://github.com/user-attachments/assets/316001f4-b856-442e-a51a-ccbda011142d)
> 
> Now I've checked the HA entity but it did not report the situation.
> 
> ![Screenshot_20241029_211024_Home Assistant](https://github.com/user-attachments/assets/539a2cdf-cf07-4a68-a89b-63eff461c768)
> 
> The other sensors like battery status are updating fine. But the smoke or CO detection is having issues.
> 
> I'm also willing to do some testing if necessary.
> 
> HA: 2024.10.2 Protect: 0.4.0b7 Auth: cookie

Alright guys, I found the issue. After I started to work with Home Assistant, I deleted everything from the Google Home app. Let's say, all devices including my "home". Everything was working fine as i used HA.

At a certain moment I got issues with my Nest thermostat so I needed to delete the device from the Nest app, run a factory default and start all other. When I added the thermostat to the Nest app I got an error message that the "home" was present in Nest but not in Google Home so there were some inconsistencies. In the back-end services of Google, those two "homes" are linked to each other. Which was my issue. 

The second time I tried to add the thermostat I got an message that the Nest app can create the same "home" in the Google Home app, as well and add all known devices. Now I have both apps with a working "home" including all the relevant Protects. Now, when I receive an firealarm, the Nest integration is registering a fire alarm from my protects. 

So apparently, the missing "homes" and inconsistencies in the back-end services of Googles messed up the Nest Protect integration. Everything works now as a charm!
