### ISSUE TITLE
v2022.11.0b0 - ERROR Unexpected exception importing platform custom_components.nest_protect.select

### ISSUE THREAD

**Issue by jazzyisj** [iMicknl/ha-nest-protect#107]
### The problem

LED brightness select not compatible with v2022.11.0

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

v2022.11.0b0

### Device / Model

Topaz-2.7 (Nest Protect Battery)

### Diagnostics information

[nest_protect-6badbf373ba688e8e2b26f1aa282240e-Nest Protect (Downstairs)-6b8df5124c35887b64d9ede2ebb85474.json.txt](https://github.com/iMicknl/ha-nest-protect/files/9883511/nest_protect-6badbf373ba688e8e2b26f1aa282240e-Nest.Protect.Downstairs.-6b8df5124c35887b64d9ede2ebb85474.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
2022-10-27 10:34:24.767 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.nest_protect.select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nest_protect/select.py", line 23, in <module>
    class NestProtectSelectDescription(
  File "/usr/local/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2022-10-27 10:34:24.774 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).
```

</details>

**Comment by velaar** [comment]
Thank you for posting! I can confirm the issue exists in my setup as well. I tried to fiddle with the code a little but no solution.

**Comment by jazzyisj** [comment]
@velaar Thanks for pointing it out, guess I didn't look close enough...
