### ISSUE TITLE
HA Core version 2022.11b1 breaks the integration

### ISSUE THREAD

**Issue by Anto79-ops** [iMicknl/ha-nest-protect#110]
### The problem

Hi all,

Looks like 2022.11b1 breaks the integration. :( 

Got some warnings to show:

```
Invalid config
The following integrations and platforms could not be set up:

nest_protect.select ([Show logs](http://homeassistant.local:8123/config/logs?filter=nest_protect.select))
Please check your config and [logs](http://homeassistant.local:8123/config/logs).

```
and

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:176
First occurred: 3:51:10 PM (5 occurrences)
Last logged: 3:52:42 PM

Error unloading entry Nest Protect for select
Error unloading entry Nest Protect for binary_sensor
Error unloading entry Nest Protect for sensor
Error unloading entry Nest Protect for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 498, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 68, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 176, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```
and

```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 3:45:22 PM (1 occurrences)
Last logged: 3:45:22 PM

Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).
```

and

```

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/nest_protect/select.py:23
Integration: Nest Protect (documentation, issues)
First occurred: 3:45:21 PM (1 occurrences)
Last logged: 3:45:21 PM

Unexpected exception importing platform custom_components.nest_protect.select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nest_protect/select.py", line 23, in <module>
    class NestProtectSelectDescription(
  File "/usr/local/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument

```

### What version of this integration (ha-nest-protect) has the issue?

0.0.38

### What version of Home Assistant Core has the issue?

2022.11.b1

### Device / Model

Nest Protect Battery

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by fishbone-git** [comment]
see bug 106

**Comment by fishbone-git** [comment]
see #106

**Comment by Anto79-ops** [comment]
Awesome I'm glad it's already known cheers!
