### ISSUE TITLE
Platform errors after HA 2022.11

### ISSUE THREAD

**Issue by tobycth3** [iMicknl/ha-nest-protect#114]
### The problem

Logger: homeassistant.setup
Source: setup.py:320
First occurred: 9:47:25 PM (1 occurrences)
Last logged: 9:47:25 PM

Unable to prepare setup for platform nest_protect.select: Platform not found (Exception importing custom_components.nest_protect.select).

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/nest_protect/select.py:23
Integration: Nest Protect (documentation, issues)
First occurred: 9:47:25 PM (1 occurrences)
Last logged: 9:47:25 PM

Unexpected exception importing platform custom_components.nest_protect.select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nest_protect/select.py", line 23, in <module>
    class NestProtectSelectDescription(
  File "/usr/local/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument

### What version of this integration (ha-nest-protect) has the issue?

0.3.8

### What version of Home Assistant Core has the issue?

core-2022.11

### Diagnostics information

![Screenshot_20221102-215610](https://user-images.githubusercontent.com/14807146/199634821-03733bb0-df89-4956-bff0-e19b38930211.png)

![Screenshot_20221102-215616](https://user-images.githubusercontent.com/14807146/199634838-c8294b41-0fb6-4e95-8f96-264c3b595c7d.png)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by nathan-curtis** [comment]
Confirm - same issue after update to 2022.11.1

**Comment by nicosaurus** [comment]
I am getting the same. Just updated to 2022.11

**Comment by wystewart** [comment]
same here. but I think the integration is still working, still has my three nest protect and the occupancy sensor changes state

**Comment by Anto79-ops** [comment]
version 0.3.9 should fix this, but there was a small detail missing that prevents you from updating to 0.3.9. should be fixed here

https://github.com/iMicknl/ha-nest-protect/issues/112

**Comment by kingzize** [comment]
Same problem in 2022.11

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/nest_protect/select.py:23
Integration: Nest Protect (documentation, issues)
First occurred: 08:47:28 (1 occurrences)
Last logged: 08:47:28

Unexpected exception importing platform custom_components.nest_protect.select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nest_protect/select.py", line 23, in <module>
    class NestProtectSelectDescription(
  File "/usr/local/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
