### ISSUE TITLE
Unexpected exception importing platform custom_components.nest_protect.select

### ISSUE THREAD

**Issue by Muzach** [iMicknl/ha-nest-protect#116]
### The problem

Log Details (ERROR)

 
This error originated from a custom integration.
Logger: homeassistant.loader
Source: custom_components/nest_protect/select.py:23 
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues)) 
First occurred: November 2, 2022 at 8:35:12 PM (1 occurrences) 
Last logged: November 2, 2022 at 8:35:12 PM

Unexpected exception importing platform custom_components.nest_protect.select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nest_protect/select.py", line 23, in <module>
    class NestProtectSelectDescription(
  File "/usr/local/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/local/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/local/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument

### What version of this integration (ha-nest-protect) has the issue?

Latest

### What version of Home Assistant Core has the issue?

2022.11.0

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by thenoid** [comment]
@Muzach I've started seeing this same issue, you opened/closed - any insight?

**Comment by Muzach** [comment]
There is an update in the HACS plug-in version that resolves the issue
