### ISSUE TITLE
Failed to Set up Error after a month of trouble free use

### ISSUE THREAD

**Issue by emersonsc** [iMicknl/ha-nest-protect#232]
### The problem

I checked my devices screen to see my Nest Protect devices have an error showing a "Failed to set up" Error. I havent changed or done anything since my initial set-up where everything worked fine. 

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

i dont know

### Device / Model

Nest Protect Battery, Nest Protect Hard Wire

### Home Assistant log

<details><summary>Logs</summary>
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect (documentation, issues)
First occurred: 3:44:43 PM (1 occurrences)
Last logged: 3:44:43 PM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

</details>

### Additional information

Home Assistant Core
2023-05-13 15:43:22.445 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-13 15:44:43.023 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nest Protect for nest_protect
File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
2023-05-13 18:08:04.475 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Nest Protect for nest_protect
File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry

**Comment by iMicknl** [comment]
This happens when you do not run version 0.3.12. Please reinstall 0.3.12 and this issue should be gone.
.

**Comment by iMicknl** [comment]
@emersonsc try to be a bit more polite next time and perhaps people actually want to help you. 

See here the code of version 0.3.12, https://github.com/iMicknl/ha-nest-protect/blob/v0.3.12/custom_components/nest_protect/__init__.py. It does not contain `async_setup_platforms`. Previous versions did contain this.

Perhaps you are using a fork where they modified the version number? Otherwise I would be clueless how you can have this error and run 0.3.12.

**Comment by emersonsc** [comment]
> @emersonsc try to be a bit more polite next time and perhaps people actually want to help you.
> 
> See here the code of version 0.3.12, https://github.com/iMicknl/ha-nest-protect/blob/v0.3.12/custom_components/nest_protect/__init__.py. It does not contain `async_setup_platforms`. Previous versions did contain this.
> 
> Perhaps you are using a fork where they modified the version number? Otherwise I would be clueless how you can have this error and run 0.3.12.

I'm not sure how I was being rude, I was simply pointing out the fact you told me to use a version I'm already running.

As far as using another fork, I don't see how that would be possible. The install was done directly for your github page using your instructions. Unless you readme files happen to have links to forks other than your own, I just dont see how that would be possible.

**Comment by iMicknl** [comment]
Can you make a zip file of the component (via your custom_components folder) and share this via email? (see my profile).

Did you install the integration manually via GitHub, or did you use HACS? When did you update the integration for the last time?

**Comment by hindsight2021** [comment]
@iMicknl if it helps, I'm having the exact same issue as OP down to the same error. I even re-installed the latest version from HACS today to re-confirm I'm up-to-date.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 1:09:54 PM (1 occurrences)
Last logged: 1:09:54 PM
Error setting up entry Nest Protect for nest_protect

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute **'async_setup_platforms'**

Happy to assist if you need anything else to evaluate this, as I find this to be a valuable integration I'd like to keep stable.

**Comment by iMicknl** [comment]
@hindsight2021 could you perhaps make the zip file as requested above? Are you sure you are using my version? Don't you have a custom repository set up in HACS? The community fork did use the same README and name, so hard to distinguish.

Did you use cookie method or the previous auth method?

**Comment by hindsight2021** [comment]
@iMicknl sent you my zipped components folder (email).

It's been a LONG time since I've set this up, but I want to say I followed your guide, I did add a custom repository, so this could be a factor.

I'm 99% sure I used the cookie method, and it was stable up until this past couple of weeks much like OP.

**Comment by iMicknl** [comment]
@hindsight2021 you are using version 0.4.0 according to your manifest.json... So not 0.3.12. You are actually using a fork, and not the code from this repository.

Please migrate back to my repository / install https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b1 manually. This version is for the cookie authentication, and doesn't break on 2023.5.

**Comment by hindsight2021** [comment]
I had a sneaking suspicion.

I've obliterated the fork, manually installed your latest beta/release in custom_components and removed the custom repository that somehow made it into my system in the past, I will attempt re-authing and advise as soon as I can. Thanks for your help!

**Comment by hindsight2021** [comment]
@iMicknl **all set,** I didn't even need to re-auth, it picked up on restart where it left off on my previous authorization before the 2023.5 update.

This will probably be OP's resolution too.

**Comment by tinoproductions** [comment]
Used 0.4.0b1 after it broke and it seems happy now

**Comment by emersonsc** [comment]
I ended up having to delete the integration from HACS. Restart HA, reinstall through HACS, then use the 0.4.0b1 version because the 0.3.12 still wouldnt work.
