### ISSUE TITLE
"Unknown pynest exception"

### ISSUE THREAD

**Issue by robertscheib** [iMicknl/ha-nest-protect#233]
### The problem

I'm receiving the three following errors in my logs, with the last saying to make an issue here.

"Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute."

"Could not interpret Nest response"

"Authentication error: invalid_request"

I only have three Nest Temperature Sensors which this integration is seeing, and I'm seeing temperature results on my dashboard.

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.5.4

### Device / Model

Nest Temperature Sensor - 3x

### Diagnostics information

```{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.5.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.11",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Chicago",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.1",
    "docker_version": "23.0.3",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "smartthinq_sensors": {
      "version": "0.26.1",
      "requirements": [
        "pycountry>=20.7.3",
        "xmltodict>=0.12.0",
        "cchardet>=2.1.7"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "nest_protect": {
      "version": "0.4.0b1",
      "requirements": []
    },
    "ha_hatch": {
      "version": "1.15.0",
      "requirements": [
        "distro>=1.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "nest_protect",
    "name": "Nest Protect",
    "codeowners": [
      "@imicknl"
    ],
    "config_flow": true,
    "dhcp": [
      {
        "macaddress": "CCA7C1*"
      }
    ],
    "documentation": "https://github.com/imicknl/ha-nest-protect",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/imicknl/ha-nest-protect/issues",
    "requirements": [],
    "version": "0.4.0b1",
    "is_built_in": false
  },
  "data": {
    "app_launch": {
      "updated_buckets": [
        {
          "object_key": "where.d8c92610-3f53-11ed-9893-0a5a54f2476d",
          "object_revision": -25611,
          "object_timestamp": 1683175801723,
          "value": {
            "wheres": [
              {
                "where_id": "00000000-0000-0000-701e-821a4cc2e891",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-e266-3c9e1fc0bb96",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000000",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000001",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000002",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000003",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000004",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000005",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000006",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000007",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000009",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000d",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000e",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000000f",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000010",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000011",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000012",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000013",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000014",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000015",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000016",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000017",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-000100000018",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001a",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001b",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001c",
                "name": "**REDACTED**"
              },
              {
                "where_id": "00000000-0000-0000-0000-00010000001d",
                "name": "**REDACTED**"
              }
            ]
          }
        },
        {
          "object_key": "kryptonite.18B430C47FC293D1",
          "object_revision": 30105,
          "object_timestamp": 1685455427630,
          "value": {
            "model": "KR1",
            "last_updated_at": 1685455426,
            "structure_id": "d8c92610-3f53-11ed-9893-0a5a54f2476d",
            "current_temperature": 22.0,
            "where_id": "00000000-0000-0000-0000-00010000000c",
            "serial_number": "**REDACTED**",
            "last_relocation_timestamp": 1667968855,
            "battery_level": 100
          }
        },
        {
          "object_key": "kryptonite.18B430C77873E8D8",
          "object_revision": -469,
          "object_timestamp": 1685449126772,
          "value": {
            "model": "KR1",
            "last_updated_at": 1685449126,
            "structure_id": "d8c92610-3f53-11ed-9893-0a5a54f2476d",
            "current_temperature": 22.5,
            "where_id": "00000000-0000-0000-e266-3c9e1fc0bb96",
            "serial_number": "**REDACTED**",
            "battery_level": 100
          }
        },
        {
          "object_key": "structure.d8c92610-3f53-11ed-9893-0a5a54f2476d",
          "object_revision": 9576,
          "object_timestamp": 1685455213569,
          "value": {
            "swarm": [
              "kryptonite.18B430CB1A53517C",
              "quartz.b7c5b537701a4a54a4181b243a03ac14",
              "kryptonite.18B430C47FC293D1",
              "kryptonite.18B430C77873E8D8",
              "quartz.839256a641974286a5505a2e0226bf0c"
            ],
            "manual_away_timestamp": 1685222514,
            "geofence_enhanced_autoaway": {
              "enabled": true,
              "is_set": true
            },
            "city": "**REDACTED**",
            "name": "**REDACTED**",
            "eta_preconditioning_active": false,
            "location": "**REDACTED**",
            "touched_by": {
              "touched_by": 0,
              "touched_id": "",
              "touched_user_id": ""
            },
            "latitude": "**REDACTED**",
            "ifj_primary_fabric_id": "**REDACTED**",
            "state": "**REDACTED**",
            "away_timestamp": 1685222514,
            "topaz_hush_key": "**REDACTED**",
            "enable_goose": false,
            "away_setter": 1,
            "phone_hush_enable": true,
            "hvac_safety_shutoff_enabled": true,
            "rcs_sensor_swarm": [
              "kryptonite.18B430C77873E8D8",
              "kryptonite.18B430C47FC293D1",
              "kryptonite.18B430CB1A53517C"
            ],
            "longitude": "**REDACTED**",
            "aux_primary_fabric_id": "**REDACTED**",
            "topaz_enhanced_auto_away_enabled": false,
            "address_lines": "**REDACTED**",
            "country_code": "US",
            "hvac_smoke_safety_shutoff_enabled": false,
            "topaz_away": false,
            "vacation_mode": false,
            "fabric_ids": [
              "9900E4497809F36A"
            ],
            "postal_code": "**REDACTED**",
            "entitlements": {},
            "dr_reminder_enabled": true,
            "members": [
              {
                "user": "**REDACTED**",
                "roles": [
                  "member"
                ]
              },
              {
                "user": "**REDACTED**",
                "roles": [
                  "owner"
                ]
              }
            ],
            "manual_eco_all": false,
            "goose_sensor_events_enabled": false,
            "time_zone": "**REDACTED**",
            "user": "**REDACTED**",
            "clutches": [],
            "away": false,
            "devices": []
          }
        },
        {
          "object_key": "kryptonite.18B430CB1A53517C",
          "object_revision": 12331,
          "object_timestamp": 1685441026928,
          "value": {
            "model": "KR1",
            "last_updated_at": 1685441027,
            "structure_id": "d8c92610-3f53-11ed-9893-0a5a54f2476d",
            "current_temperature": 23.59999,
            "where_id": "00000000-0000-0000-0000-000100000005",
            "serial_number": "**REDACTED**",
            "battery_level": 100
          }
        }
      ],
      "service_urls": {
        "urls": {
          "rubyapi_url": "https://home.nest.com/",
          "czfe_url": "https://czfe24-front01-iad01.transport.home.nest.com",
          "log_upload_url": "https://logsink.home.nest.com/upload/user",
          "transport_url": "https://czfe24-front01-iad01.transport.home.nest.com",
          "weather_url": "https://apps-weather.nest.com/weather/v1?query=",
          "support_url": "https://nest.secure.force.com/support/webapp?",
          "direct_transport_url": "https://transport04-rts19-iad01.transport.home.nest.com:443"
        },
        "limits": {
          "thermostats_per_structure": 20,
          "structures": 5,
          "smoke_detectors_per_structure": 18,
          "smoke_detectors": 54,
          "thermostats": 60
        },
        "weave": {
          "service_config": "**REDACTED**",
          "pairing_token": "**REDACTED**",
          "access_token": "**REDACTED**"
        }
      },
      "weather_for_structures": {
        "structure.d8c92610-3f53-11ed-9893-0a5a54f2476d": {
          "current": {
            "icon": "partlycloudy",
            "temp_c": "**REDACTED**",
            "sunrise": "**REDACTED**",
            "sunset": "**REDACTED**"
          },
          "location": "**REDACTED**"
        }
      },
      "2fa_enabled": true
    }
  }
}
```

### Home Assistant log

<details><summary>Logs</summary>
```
2023-05-30 08:28:24.560 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-05-30 08:28:24.601 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-05-30 08:28:24.606 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
```

</details>

**Comment by robertscheib** [comment]
Yes, I am using the cookie method.

**Comment by nigelayen** [comment]
I am seeing this error as well, however, the integration seems to be working for my two Nest Protect smoke detectors. Here is the log:
`This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:224 
Integration: Nest Protect (documentation, issues) 
First occurred: May 30, 2023 at 5:19:19 PM (88 occurrences) 
Last logged: 10:39:44 AM

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
`

**Comment by tj335** [comment]
Was just coming here to create an issue for this error as well.  I'm using the cookie method.

**Comment by rhdny** [comment]
Same here. Seeing those three errors. 

Everything is working fine, other than the note in the logs about updates being paused for 1 min each time the errors occur.

**Comment by jackpenny101** [comment]
Same issue - everything is working fine but logs show the same error.

**Comment by m4v3r1ckNl** [comment]
Thanks for this Nest Protect integration as it is working perfect, but logfile showing similar issues.

### **Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.**

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:224
Integration: Nest Protect (documentation, issues)
First occurred: 12:30:54 (11 occurrences)
Last logged: 22:51:41

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.

```
### **Could not interpret Nest response**

```
This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:222
Integration: Nest Protect (documentation, issues)
First occurred: 12:30:54 (11 occurrences)
Last logged: 22:51:41

Could not interpret Nest response
```
 ### **Authentication error: invalid_request**

```
This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:214
Integration: Nest Protect (documentation, issues)
First occurred: 12:30:54 (11 occurrences)
Last logged: 22:51:41

Authentication error: invalid_request
```
### **Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.**

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:302
Integration: Nest Protect (documentation, issues)
First occurred: August 1, 2023 at 12:29:54 (11 occurrences)
Last logged: August 1, 2023 at 22:50:41

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 298, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 73, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe05-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 166, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 302, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 

```

**Comment by hoorna** [comment]
The same situation here. The integration seems to be working fine but with the by others reported errors.

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
