### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by Pandabeer40** [iMicknl/ha-nest-protect#237]
### The problem

This evening the integration stopped - No devices or entities / setup failed

restarting HA was not helping - deinstall it from HACS - reinstalled it - HA saw a new NEST integration - with the readme I provided a issue token  and cookies - these setting were accepted, but the intregration gave the same error message No devices or entities.

It was working without any changes till this evening

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b1

### What version of Home Assistant Core has the issue?

2023.6.2

### Device / Model

Nest Protect powerline

### Diagnostics information

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect (documentation, issues)
First occurred: 21:59:38 (2 occurrences)
Last logged: 22:03:41

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
See https://github.com/iMicknl/ha-nest-protect/issues/232. You are using a fork, not my version. Remove the fork from HACS custom repositories and install the latest **beta** of my repository.

**Comment by Pandabeer40** [comment]
Thnx – it looks like it’s working again

 

Van: Mick Vleeshouwer ***@***.***> 
Verzonden: maandag 19 juni 2023 22:19
Aan: iMicknl/ha-nest-protect ***@***.***>
CC: Pandabeer40 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [iMicknl/ha-nest-protect] No devices or entities (Issue #237)

 

See #232 <https://github.com/iMicknl/ha-nest-protect/issues/232> . You are using a fork, not my version. Remove the fork from HACS custom repositories and install the latest beta of my repository.
