### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by rronni** [iMicknl/ha-nest-protect#243]
### The problem

Installed and working for several months, however logging on to check today i'm seeing an error "Failed to setup". Have installed the latest update, however same error occurs.

From logs:
Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 17:59:31 (1 occurrences)
Last logged: 17:59:31

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.7.1

### Device / Model

Topaz-2.33 - Nest Protect WIred

### Diagnostics information

Shows as unavailable following HACore Update - also updated ha-nest-protect integration, but still shoiws as "unavailable" logs attached.
Thanks!

### Home Assistant log

<details><summary>Logs</summary>
```
Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: 17:59:31 (1 occurrences)
Last logged: 17:59:31

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

</details>

### Additional information

n/a

**Comment by iMicknl** [comment]
You are probably using a fork of this integration (a modified copy) and not the original integration. Did you install it through HACS?

Have a look at custom repositories and remove the other repository. Now reinstall the latest version from this integration.

**Comment by rronni** [comment]
![image](https://github.com/iMicknl/ha-nest-protect/assets/66040518/92f4a285-633f-42a8-904f-f7465fe21966)

Same error when installing via HACS or manual from here sadly...

**Comment by iMicknl** [comment]
@rronni which version do you install manually? You are not the first user to report this, and all users did use another repository than https://github.com/iMicknl/ha-nest-protect. Are you sure you don't have any custom repositories configured in HACS?

**Comment by rronni** [comment]
![image](https://github.com/iMicknl/ha-nest-protect/assets/66040518/7e75bf26-7c7f-4364-8112-503219a20bd0)
This is all I have currently under HACS - All were installed previously when this was working well. Not sure the exact date of when it stopped working. 

Happy to check anything else you can suggest - I've removed the Nest Protect integration using the "Delete" option here: 
![image](https://github.com/iMicknl/ha-nest-protect/assets/66040518/e244aa9b-80b3-45d1-b821-2ac966ec35f0)

But it seems to fail to setup every time...

Thanks!

**Comment by iMicknl** [comment]
What about the following option:
<img width="184" alt="image" src="https://github.com/iMicknl/ha-nest-protect/assets/1424596/1f0687da-ca9c-4d2a-9c87-cbc3967d3046">.

Otherwise you can also just download the latest version from this component from GitHub and place it in your custom_component folder.

**Comment by rronni** [comment]
Managed to navigate to and remove the old Custom Integration from storage directly. Was no trace of it in the HA UI.

Reinstalled, and now unable to link my google account. Remember having a similar issue the last time, so off to read up on this: 
![image](https://github.com/iMicknl/ha-nest-protect/assets/66040518/91a60add-d35c-410b-9c41-e407c4f165b4)


Thanks for your help so far! :)

**Comment by iMicknl** [comment]
You will need the beta version if you are a new user: https://github.com/iMicknl/ha-nest-protect/releases/tag/v0.4.0b2.

Instructions here: https://github.com/iMicknl/ha-nest-protect/tree/v0.4.0b2#retrieving-issue_token-and-cookies.

**Comment by rronni** [comment]
Golden - thanks for your help!

![image](https://github.com/iMicknl/ha-nest-protect/assets/66040518/7e0dc5c8-1adb-4e48-8f40-f444f602a322)
