### ISSUE TITLE
Log Error - Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.

### ISSUE THREAD

**Issue by HiImTemmy** [iMicknl/ha-nest-protect#248]
### The problem

I recently installed the Nest Protect Integration (v0.4.0b2) to HA (2023.8.1). I followed the instructions for cookie authentication, and my Nest Protect successfully shows on my dashboard. However, my log is getting hit by the following:

![image](https://github.com/iMicknl/ha-nest-protect/assets/83087378/b57b83a0-64e2-4533-abda-3169859c5d88)

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b2

### What version of Home Assistant Core has the issue?

2023.8.1

### Device / Model

Topaz-2.9 by Google Firmware: 3.5rc3 Hardware: Wired

### Diagnostics information

[config_entry-nest_protect-9a1f9846eae33968c62c4f9daa5fa9d2.json.txt](https://github.com/iMicknl/ha-nest-protect/files/12266478/config_entry-nest_protect-9a1f9846eae33968c62c4f9daa5fa9d2.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
2023-08-04 22:55:45.680 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-04 22:55:45.683 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-04 22:59:10.997 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:06:59.232 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:09:38.758 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:23:05.346 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:29:11.422 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:38:10.583 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:54:13.582 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:59:11.743 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-04 23:59:11.748 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-04 23:59:12.365 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-04 23:59:12.377 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-04 23:59:12.379 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 00:00:12.780 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 00:00:12.781 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 00:29:11.972 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 00:59:12.820 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 01:29:12.175 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 01:29:12.179 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-05 01:29:13.251 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-05 01:29:13.254 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-05 01:29:13.258 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 01:30:13.659 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 01:30:13.659 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 01:59:12.372 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 02:29:12.435 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 02:59:12.936 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 02:59:12.942 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-05 02:59:14.080 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-05 02:59:14.083 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-05 02:59:14.088 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 03:00:14.493 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 03:00:14.494 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 03:29:12.730 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 03:59:12.926 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 04:29:13.053 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 04:29:13.058 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-05 04:29:14.110 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-05 04:29:14.114 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-05 04:29:14.117 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 04:30:14.521 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 04:30:14.521 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 04:59:13.178 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 05:29:13.668 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 05:59:13.683 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 05:59:13.687 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-05 05:59:15.319 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-05 05:59:15.323 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-05 05:59:15.325 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 06:00:15.729 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 06:00:15.730 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 06:29:14.006 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 06:59:14.990 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 07:29:14.159 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 07:29:14.163 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2023-08-05 07:29:15.381 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-08-05 07:29:15.385 ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
2023-08-05 07:29:15.388 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 163, in _async_subscribe_for_data
    entry_data.client.nest_session = await entry_data.client.authenticate(auth)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials"}. Please create an issue on GitHub.
2023-08-05 07:30:15.789 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 401
2023-08-05 07:30:15.789 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: 401 exception.
2023-08-05 07:59:14.401 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 08:07:17.697 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200
2023-08-05 08:22:49.993 DEBUG (MainThread) [custom_components.nest_protect.pynest] Got data from Nest service 200

```

</details>

**Comment by matth08080808** [comment]
I'm getting the same errors, can't work out why as the device is accessible.

**Comment by stiltjack** [comment]
Same here. Each one is followed by:

`This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:222
Integration: Nest Protect (documentation, issues)
First occurred: 23:29:37 (1 occurrences)
Last logged: 23:29:37

Could not interpret Nest response`

And then:

`This error originated from a custom integration.

Logger: custom_components.nest_protect.pynest
Source: custom_components/nest_protect/pynest/client.py:214
Integration: Nest Protect (documentation, issues)
First occurred: 23:29:37 (1 occurrences)
Last logged: 23:29:37

Authentication error: invalid_request`

Configuration switches and diagnostic entities appear to be working, but it's a bit concerning as I can't see any way to test the sensors themselves, which haven't been updated since installation this afternoon. Without an actual fire, I'm assuming they're updated once every 24 hours when the Nest Protect does its check?

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

**Comment by Lampyridae1984** [comment]
+1

Not sure why, it seems to work just fine.

**Comment by B-double-U** [comment]
Same behavior here.
Seems to happen every hour. 
All works though. 

Home Assistant 2023.10.2
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**Comment by iMicknl** [comment]
Please update to latest beta (now v0.4.0b5) and create a new issue if you face issues.
