### ISSUE TITLE
login succeeded, but device setup fails and says my linkage has no devices

### ISSUE THREAD

**Issue by Diddz7** [iMicknl/ha-nest-protect#252]
### The problem

I am using a fork that allows pasting of the token and cookie, the login was successful ( HA added the integration to the device list ) but none of my 7 protect's show up and the integration indicates no entities of devices with a failed to set up error

### What version of this integration (ha-nest-protect) has the issue?

0.3.12

### What version of Home Assistant Core has the issue?

2023.7.1 Frontend 20230705.1 - latest

### Device / Model

Nest Protect (Battery)

### Home Assistant log

<details><summary>Logs</summary>
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nest_protect/__init__.py:126
Integration: Nest Protect (documentation, issues)
First occurred: 11:42:03 AM (4 occurrences)
Last logged: 11:50:54 AM

Error setting up entry Nest Protect for nest_protect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/__init__.py", line 126, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
![Screenshot_445](https://github.com/iMicknl/ha-nest-protect/assets/140991292/77bad08d-50d1-4db7-8a23-9b9d9628b2c8)

```

</details>

**Comment by iMicknl** [comment]
Please use latest beta instead of the fork.
