### ISSUE TITLE
[BETA] Can't Add New Integration via Cookie Auth

### ISSUE THREAD

**Issue by bmos** [iMicknl/ha-nest-protect#291]
### The problem

When I try to add the integration via Field Test login, I get this and cannot continue:
![Unexpected Error](https://github.com/iMicknl/ha-nest-protect/assets/1916835/dacbc486-218e-435c-b653-3d612e676efd)

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b4

### What version of Home Assistant Core has the issue?

2023.12.4

### Device / Model

Nest Protect (Wired)

### Home Assistant log

<details><summary>Logs</summary>

```
2023-12-27 18:33:55.484 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nest_protect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-27 18:35:59.771 ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
2023-12-27 18:35:59.772 ERROR (MainThread) [custom_components.nest_protect] 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"98732789-6fbc-4978-904b-9ab7734420c2"}. Please create an issue on GitHub.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 217, in authenticate
    self.nest_session = NestResponse(**nest_response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NestResponse.__init__() got an unexpected keyword argument 'error_description'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/config_flow.py", line 103, in async_step_account_link
    [issue_token, cookies, user] = await self.async_validate_input(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/config_flow.py", line 63, in async_validate_input
    response = await client.authenticate(auth.access_token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 224, in authenticate
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while authenticating - {"error":"invalid_request","error_description":"missing user credentials","instance_id":"98732789-6fbc-4978-904b-9ab7734420c2"}. Please create an issue on GitHub.
```
</details>

**Comment by bmos** [comment]
I'm not entirely sure what Field Test means, but that was the issue.
Don't use Field Test unless you know what you're doing I guess.

**Comment by iMicknl** [comment]
I will see if we can improve the description for environment, but this error should be different as well. Let me have a look.

**Comment by titis14** [comment]
Hi, I also tested this method but I don't get issuetoken when I log in. I find that the cookie.
It's a shame to have so much difficulty installing such security equipment in our home automation.

**Comment by titis14** [comment]
Hi, following my message I managed to integrate my Nest protect, thank you for this version. I did not check Preserve Log.

**Comment by Frazou1** [comment]
Any news about this ?  There is another way to integrate it ?

**Comment by titis14** [comment]
I had no problem integrating it with the beta version.

**Comment by Frazou1** [comment]
> I had no problem integrating it with the beta version.

Oh where is the beta version ?

**Comment by bmos** [comment]
Install via HACS:
1. Open the integration in HACS and click the three dots
![image](https://github.com/iMicknl/ha-nest-protect/assets/1916835/28998302-7cec-4c5b-b009-ef7b22304840)
2. Click Redownload
3. Enable show beta downloads and download the latest beta release
![image](https://github.com/iMicknl/ha-nest-protect/assets/1916835/6bff00d4-2632-42aa-b253-bba9dfc0e0f3)

**Comment by markusd1984** [comment]
I got the same error using I think the latest beta verison 0.4.0b8

regardless it seem to have worked/authenticated since the data is updating again and showing on the dashboard.

Btw. it would help to have the info about issueToken/oauth2/iframe displayed right in the login dialogue rather than only linking to the readme, to save time, as after a HA reboot it needs to be done again and again. =)
