### ISSUE TITLE
HA 2024.1.0: Unknown pynest exception

### ISSUE THREAD

**Issue by poudenes** [iMicknl/ha-nest-protect#295]
### The problem

Hi There,

After update to HA.2024.1.0 I see a error pop-up

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b4

### What version of Home Assistant Core has the issue?

2024.1.0

### Device / Model

Topaz-2.7

### Home Assistant log

```
2024-01-05 09:56:39.008 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 298, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 71, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe49-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 168, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 302, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
```

**Comment by thargy** [comment]
Yeah, I'm seeing this too.

**Comment by poudenes** [comment]
Here some other error log lines

```
2024-01-10 13:40:11.049 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 298, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 71, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe78-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 168, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 302, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
2024-01-10 14:35:51.622 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-01-10 14:35:51.623 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-01-10 14:35:51.623 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-01-10 14:35:51.623 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-01-10 14:41:13.768 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 298, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 71, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe78-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 168, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 302, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
```

**Comment by newbyp** [comment]
I get the same errors too, they seem to happen every couple of hours.

**Comment by poudenes** [comment]
Here some moments of the error. I have enabled the Debug mode now will post this when there are some lines.

```
2024-01-11 14:30:14.696 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 15:31:18.078 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 16:32:23.108 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 17:33:27.825 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 18:34:30.882 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 19:35:33.974 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 20:36:37.041 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 21:37:40.836 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 22:38:45.054 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 23:39:48.899 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 23:49:59.169 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 23:51:00.147 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 23:52:01.038 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-11 23:53:02.030 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 01:21:07.677 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 02:22:11.130 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 03:23:14.016 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 04:24:17.224 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 06:09:33.349 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 07:10:36.559 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 08:11:39.799 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
2024-01-12 09:12:43.325 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
```

**Comment by poudenes** [comment]
Here debug log

```
2024-01-12 11:51:42.714 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 298, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 71, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1165, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe04-front01-iad01.transport.home.nest.com/v6/subscribe')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 168, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 302, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
2024-01-12 11:52:42.723 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 11:57:42.972 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 11:57:42.976 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:02:43.156 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:02:43.158 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:07:43.398 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:07:43.399 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:12:43.711 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:12:43.714 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:17:43.952 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:17:43.956 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:22:44.191 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:22:44.196 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:27:44.944 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:27:44.946 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
2024-01-12 12:32:45.140 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 162, in _async_subscribe_for_data
    auth = await entry_data.client.get_access_token()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 82, in get_access_token
    await self.get_access_token_from_cookies(self.issue_token, self.cookies)
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
2024-01-12 12:32:45.144 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: retrieving new Google access token
```

**Comment by poudenes** [comment]
It worked for 1 day with several restarts of HA. Now 13-01-2024 this morning updated HA to new version and the integration was broken again. I disabled the integration (to prevent possibility that my account will blocked by Google)

**Comment by iMicknl** [comment]
Thanks all! Part of the errors mentioned in this issue are already part of other issues, and still need to be taken care of. The reason that this part of the integration is still in beta, is due to these errors and the cookie method not being optimal. I haven't written this code, but hope to have the coming months some more time to work on improving this.

>It worked for 1 day with several restarts of HA. Now 13-01-2024 this morning updated HA to new version and the integration was broken again. I disabled the integration (to prevent possibility that my account will blocked by Google)

Most likely this is due to your cookie expiring, but I agree it is not optimal. At the moment there is no reauth flow yet, thus not easy to reconfigure the authentication when the "USER_LOGGED_OUT" error is raised.

**Comment by poudenes** [comment]
> Thanks all! Part of the errors mentioned in this issue are already part of other issues, and still need to be taken care of. The reason that this part of the integration is still in beta, is due to these errors and the cookie method not being optimal. I haven't written this code, but hope to have the coming months some more time to work on improving this.
> 
> > It worked for 1 day with several restarts of HA. Now 13-01-2024 this morning updated HA to new version and the integration was broken again. I disabled the integration (to prevent possibility that my account will blocked by Google)
> 
> Most likely this is due to your cookie expiring, but I agree it is not optimal. At the moment there is no reauth flow yet, thus not easy to reconfigure the authentication when the "USER_LOGGED_OUT" error is raised.

Will it help to keep the Crome 24/7 open on the PC/MacOS for now when you get the information for the integration. So browsing is ok, but never close it? I can keep open the Chrome browser and move it to a second virtual screen on MacOS and leave it there....
