### ISSUE TITLE
Failed Setup will retry on latest beta and current HA build

### ISSUE THREAD

**Issue by hesspoint** [iMicknl/ha-nest-protect#315]
### The problem

I am running the beta v0.4.0b4 for quite a while not and could connect using the issue token and cookie. That was working well for quite some time. With the latest update of HA 2024.2.3 it suddenly stopped working and says Failed Setup will retry. Also restart won't fix it.

I tried to click "add entry" and I grabbed and pasted the issue token and cookie again (as per instructions). Then I got the error message that an entry already exists and that's it, Still does not work

### What version of this integration (ha-nest-protect) has the issue?

v0.4.0b4

### What version of Home Assistant Core has the issue?

2024.2.5

### Device / Model

Nest Protect Battery

### Home Assistant log

<details><summary>Logs</summary>

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:80
Integration: Nest Protect ([documentation](https://github.com/imicknl/ha-nest-protect), [issues](https://github.com/imicknl/ha-nest-protect/issues))
First occurred: March 4, 2024 at 17:40:32 (1156 occurrences)
Last logged: 19:29:22

Unknown exception.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 80, in async_setup_entry
    auth = await client.get_access_token_from_cookies(issue_token, cookies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 158, in get_access_token_from_cookies
    raise Exception(result["error"])
Exception: USER_LOGGED_OUT
</details>

**Comment by hesspoint** [comment]
Ok I now solved it on my own the hard way. As I could not reconfigure and would always get this "entry already configured" message, I simply took the plunge und deleted all my nest devices from the config und then setup from scratch and then it worked.

No idea what happened there before
