### ISSUE TITLE
Unknown Exception - 'list' object has no attribute 'object_key'

### ISSUE THREAD

**Issue by Matsuo3rd** [iMicknl/ha-nest-protect#338]
### The problem

Under v0.4.0b5 / HA 2024.6.3, every 5 minutes, the following error pops:

2024-06-17 19:21:10.772 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:26:11.491 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:31:12.226 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.6.3

### Home Assistant log

<details><summary>Logs</summary>

```
2024-06-17 19:21:10.772 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:26:11.491 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-06-17 19:31:12.226 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
```
</details>

**Comment by styphonthal** [comment]
I have similar error: 
2024-06-17 16:41:37.516 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by iMicknl** [comment]
Thanks both! I indeed can reproduce this, but haven't been able to figure out yet what is going wrong exactly.

**Comment by B-double-U** [comment]
FYI:

Same here.
Just sharing in case this might help.

> This error originated from a custom integration.
> 
> Logger: custom_components.nest_protect
> Source: custom_components/nest_protect/__init__.py:208
> integration: Nest Protect (documentation, issues)
> First occurred: June 17, 2024 at 10:53:26 (2240 occurrences)
> Last logged: 11:42:57
> 
> Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
> Traceback (most recent call last):
>   File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
>     dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
>                           ^^^^^^^^^^^^
> AttributeError: 'list' object has no attribute 'object_key'
>

**Comment by meanaverage** [comment]
Same here. Was killing my motion sensor light automations.

I ran the error and the __init__.py through GPT 4o and it was able to identify the issue and fix it.

Here are the lines that were changed along with their line numbers:

Line 5: Importing dict from typing.
`from typing import dict`

Line 208: Corrected the list comprehension to properly iterate over data.updated_buckets.
`objects = [
    dict(b, **buckets.get(b.object_key, {})) for b in data.updated_buckets
]`


Additionally, I corrected the type hint for areas in the HomeAssistantNestProtectData dataclass:

Line 46: Corrected the type hint for areas.

`areas: dict[str, str]`

These are the primary changes made to resolve the issue with handling the data.updated_buckets list.

**Comment by meanaverage** [comment]
Maybe this worked. Haven't received the error in a while and my occupancy sensor automations are working again.

<img width="796" alt="image" src="https://github.com/iMicknl/ha-nest-protect/assets/18336095/09b6a48d-b4b0-4d1b-a521-e2748f1c6417">

**Comment by iMicknl** [comment]
This is a known issue. Hopefully I can have a look soon to fix this. No need to reply with 'same issue', feel free to do a thumbs up on original post if you face the same issue.

**Comment by iSteve-O** [comment]
This issue resolves itself on my system every time after a reboot, but always requires a full reboot of home assistant. The error that pauses updates for 1 minute seems to correct itself and doesn't require a restart to begin to function again.

**Comment by janusn** [comment]
I encounter similar this bug.

Albeit errors are logged, the nest_protect devices continue to report status.

**Comment by Matsuo3rd** [comment]
Issue fixed once upgraded to latest beta (including https://github.com/iMicknl/ha-nest-protect/pull/355)

**Comment by lordbah** [comment]
Really? I didn't see any new release notes and couldn't even find any new commits when I looked yesterday.

**Comment by Matsuo3rd** [comment]
See https://github.com/iMicknl/ha-nest-protect/tree/beta (beta branch)
You need to change HACS repo link to the beta one.

**Comment by lordbah** [comment]
What I mean by that is the HA Settings update looks like this:
![Screenshot from 2024-10-01 20-42-00](https://github.com/user-attachments/assets/95059e96-cbf0-4c89-8ea0-3daf255b62ae)
It's for v0.4.0b6 but that's the same "What's changed" text it's had for a couple of years and doesn't mention anything new, right? If that version has a potential fix for issues I would expect to see it there, to encourage people facing issues to install it.
About the commits you are of course correct, when I change from "main" to "beta" on github I can see very recent commits.
I can't find anywhere in HACS to change the URL of a repository. Do I have to Remove it and add it back again, selecting a different version? On the other hand, if it's already offering me v0.4.0b6 then maybe I don't need to change it.

**Comment by iMicknl** [comment]
Reopened this issue due to issues with the fix. Would be good to update as soon as possible to v0.4.0b7 (see release information).

**Comment by lordbah** [comment]
With v0.4.0b7:
```
2024-10-05 18:21:45.782 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 317, in subscribe_for_data
    result = await response.json()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 200, message='Attempt to decode JSON with unexpected mimetype: text/plain', url='https://czfe50-front01-iad01.transport.home.nest.com/v6/subscribe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 169, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nest_protect/pynest/client.py", line 321, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing -
```

**Comment by Maarc** [comment]
Hi there,

I have similar issues with v0.4.0b7.

Every 5 minutes, I get the following error in my home assistant log file:

```
2024-10-10 15:35:27.004 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
```

**Comment by puterboy** [comment]
I also have this issue running v0.4.0b7
Is there any solution in sight?

**Comment by iMicknl** [comment]
@puterboy I don't have time to fix this, however it is only a warning and shouldn't influence the working of the integration. Happy to accept any (tested) PRs.

**Comment by ScottESanDiego** [comment]
Isn't that the same root cause as #364 and the like (delayed presence notifications)?

**Comment by iMicknl** [comment]
@ScottESanDiego not sure if I understand your question? The revert in #364 was because this contributed fix did cause side effects and hit the Nest servers massively.

**Comment by genehand** [comment]
The HA error message says "Updates paused for 5 minutes".  I confirmed that my HA occupancy sensor doesn't trigger for up to a few minutes while homebridge picks it up almost immediately.

**Comment by ScottESanDiego** [comment]
> @ScottESanDiego not sure if I understand your question? The revert in #364 was because this contributed fix did cause side effects and hit the Nest servers massively.

I was replying to your ( @iMicknl ) statement above of "owever it is only a warning and shouldn't influence the working of the integration.".  I don't believe that is true - it's an error and changes the working of the integration at least insomuch as notifications are delayed.

I agree, the fix to #364 wasn't a good fix and you were right to revert it, just think the issue in this bug is the same root case and impact as the other bugs (like #364 ).

**Comment by Mark612** [comment]
2024-10-23 14:27:17.710 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by dtremere** [comment]
I have been getting it for a while now also:

This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/__init__.py:208
integration: Nest Protect (documentation, issues)
First occurred: 11:58:29 AM (24 occurrences)
Last logged: 2:00:54 PM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

**Comment by ScottESanDiego** [comment]
FWIW, the error is different after recent HA updates.  Still doesn't work, and errors in the same geenral area...but a slightly different error.

```
2024-11-23 14:56:25.545 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 213, in _async_subscribe_for_data
    dict(item, **buckets.get(b.object_key, {}))
ValueError: dictionary update sequence element #0 has length 13; 2 is required
```

**Comment by iMicknl** [comment]
Should be fixed in the latest beta. Please update to the latest version and create a new issue if you face any issues.
