### ISSUE TITLE
Unknown exception after latest update

### ISSUE THREAD

**Issue by tankdeer** [iMicknl/ha-nest-protect#351]
### The problem

Started receiving these after updating to the latest beta version

### What version of this integration (ha-nest-protect) has the issue?

0.4.0b5

### What version of Home Assistant Core has the issue?

2024.8.3

### Device / Model

Hardwired

### Diagnostics information

[nest_protect-fe613734dbd943f3ebef3cd29efb2da8-Nest Protect (Upstairs)-19171b161b62b6a509a03edaf3e40cc8.json](https://github.com/user-attachments/files/16753030/nest_protect-fe613734dbd943f3ebef3cd29efb2da8-Nest.Protect.Upstairs.-19171b161b62b6a509a03edaf3e40cc8.json)

### Home Assistant log

<details><summary>Logs</summary>

```
2024-08-26 10:34:49.711 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-08-26 10:39:50.155 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-08-26 10:44:50.581 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'
2024-08-26 10:49:51.024 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 208, in _async_subscribe_for_data
    dict(b, **buckets.get(b.object_key, {})) for b in [data.updated_buckets]
                          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'object_key'

```
</details>

**Comment by nandi95** [comment]
Is there a previous version I can roll back to where it works? what's the git hash?

**Comment by iMicknl** [comment]
One earlier release.. 😉

**Comment by nandi95** [comment]
![Screenshot 2024-08-30 at 09 02 05](https://github.com/user-attachments/assets/c343930b-0c0f-493b-865d-a4ce79e7f00f)
unfortunately that didn't work either
