### ISSUE TITLE
Heat Test entity showing 'Problem'

### ISSUE THREAD

**Issue by Daneish** [iMicknl/ha-nest-protect#50]
### The problem

The Nest Protect Heat Test problem entity is in `on`/`Problem` status however the Nest iOS app / web portal are reporting `Everything is ok`.

Manually running a test on the Protect in the Nest app, again reports everything is ok.

All of the other Protect entities (including Heat Status) are reporting as `Normal`/`Clear`/`off`. Restarting HA has no effect on the Heat Test status.

I'm not sure this is definitely a bug, but it would be good to get confirmation if there is actually any problems with the Protect.

Also, I'm unsure if related, but I have also intermittently been getting a `Subscriber: pynest exception.` `504 error while subscribing` errors (full error in logs section below). I've just enabled debug logging, but haven't had the subscriber error again yet, I'll update this issue when I do.

I'm running:
Topaz-2.9
Firmware: 3.4rc6
Hardware: Battery
Nest Protect integration v0.3.2 (installed through HACS).
Home Assistant Core: 2022.3.2
Supervisor: 2022.03.2
Home Assistant OS: 7.4
Hardware: Raspberry Pi 4b

Thanks again for this great integration, please let me know if I can provide any more information or testing to help.

### What version of this integration (ha-nest-protect) has the issue?

0.3.2

### What version of Home Assistant Core has the issue?

2022.3.2

### Device / Model

Nest Protect Gen 2 (Battery)

### Diagnostics information

[nest_protect-7a61ef255ac5b08dafd74d4a416fb65b-Nest Protect (Hallway)-18d203211781153d9ee3fe1c9cf13212 Custom Redacted.json.txt](https://github.com/iMicknl/ha-nest-protect/files/8243894/nest_protect-7a61ef255ac5b08dafd74d4a416fb65b-Nest.Protect.Hallway.-18d203211781153d9ee3fe1c9cf13212.Custom.Redacted.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
2022-03-14 20:54:01 ERROR (MainThread) [custom_components.nest_protect] Subscriber: pynest exception.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/pynest/client.py", line 238, in subscribe_for_data
result = await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://czfe21-front01-iad01.transport.home.nest.com/v6/subscribe')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 128, in _async_subscribe_for_data
result = await entry_data.client.subscribe_for_data(
File "/config/custom_components/nest_protect/pynest/client.py", line 242, in subscribe_for_data
raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 504 error while subscribing - <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>


```

</details>

### Additional information

N/A

**Comment by iMicknl** [comment]
```json
{
	"object_key": "topaz.6416660000D226BE",
	"object_revision": -4261,
	"object_timestamp": 1647231127646,
	"value": {
		"spoken_where_id": "00000000-0000-0000-0000-000100000002",
		"creation_time": 1607066663156,
		"installed_locale": "en_GB",
		"ntp_green_led_brightness": 1,
		"component_buzzer_test_passed": true,
		"wifi_ip_address": "10.10.20.110",
		"wired_led_enable": true,
		"wifi_regulatory_domain": "A1",
		"co_blame_duration": 0,
		"is_rcs_capable": false,
		"fabric_id": "D24DD109A807CA56",
		"battery_health_state": 0,
		"steam_detection_enable": true,
		"hushed_state": false,
		"capability_level": 2.0,
		"home_alarm_link_type": 0,
		"model": "Topaz-2.9",
		"component_smoke_test_passed": true,
		"component_speaker_test_passed": true,
		"removed_from_base": false,
		"smoke_sequence_number": 0,
		"home_away_input": true,
		"device_locale": "en_GB",
		"co_blame_threshold": 0,
		"kl_software_version": "3.1.4",
		"component_us_test_passed": false,
		"auto_away": true,
		"night_light_enable": true,
		"component_als_test_passed": true,
		"speaker_test_results": 32768,
		"wired_or_battery": 1,
		"is_rcs_used": false,
		"replace_by_date_utc_secs": 1887753600,
		"certification_body": 3,
		"component_pir_test_passed": true,
		"structure_id": "d626c2e0-0eeb-11eb-a5b1-1296659e164a",
		"software_version": "3.4rc6",
		"component_hum_test_passed": true,
		"home_alarm_link_capable": false,
		"night_light_brightness": 1,
		"device_external_color": "white",
		"latest_manual_test_end_utc_secs": 1647230851,
		"smoke_status": 0,
		"latest_manual_test_start_utc_secs": 1647230807,
		"component_temp_test_passed": true,
		"home_alarm_link_connected": false,
		"co_status": 0,
		"heat_status": 0,
		"product_id": 9,
		"night_light_continuous": false,
		"co_previous_peak": 0,
		"auto_away_decision_time_secs": 600,
		"component_co_test_passed": true,
		"where_id": "00000000-0000-0000-0000-000100000002",
		"serial_number": "**REDACTED**",
		"component_heat_test_passed": false,
		"latest_manual_test_cancelled": false,
		"thread_mac_address": "**Custom REDACTED**",
		"resource_id": "topaz_resource.5",
		"buzzer_test_results": 32768,
		"wifi_mac_address": "**Custom REDACTED**",
		"line_power_present": false,
		"gesture_hush_enable": false,
		"device_born_on_date_utc_secs": 1572134400,
		"ntp_green_led_enable": true,
		"component_led_test_passed": true,
		"co_sequence_number": 0,
		"thread_ip_address": "**REDACTED**",
		"component_wifi_test_passed": true,
		"heads_up_enable": true,
		"battery_level": 5181
	}
}```

You have the same as me, the status of `component_heat_test_passed` is set to `false`... I don't see any warnings in the Nest app as well, thus I wonder if we should include this value, or if this is not used by the app anymore.

I see you redacted the `weather_for_structures` and some other values as well, I will include that one to the redaction engine in an upcoming update. Makes sense, since this could also be used to identify a location. 

The 504 error is not related and tracked in https://github.com/iMicknl/ha-nest-protect/issues/34. The latest release should already include some improvements for this.

**Comment by poudenes** [comment]
Have same issue.. I was thinking I have old devices.

**Comment by Daneish** [comment]
It seems likely that component_heat_test_passed may no longer be used. Searching Google for component_heat_test_passed doesn’t yield many results and none specifically talk about the parameter, they are all just config dumps or screenshots.

A couple of results from [2015](https://community.smartthings.com/t/nest-protect-device-type/4018/120?page=7) and [2016](https://github.com/bwssytems/ha-bridge/issues/44#issuecomment-193912135) show ` "component_heat_test_passed":true`, but results from [2018](https://pastebin.com/fG4dcDfH) and [2020](https://thingsthataresmart.wiki/index.php?title=My_Next_Alarm) have the same `false` result as us.

Looking at the docs for the Home Assistant deprecated [Works with Nest API](https://www.home-assistant.io/integrations/nest/) and the [HomeBridge-nest](https://github.com/chrisjshull/homebridge-nest) it appears like neither of these projects exposed the `component_heat_test_passed` value, but I have not gone through the code to confirm that. Hard to tell if the project’s developers excluded it specifically because it was invalid, or it just wasn’t data they cared about.

The [Nest API documentation](https://developers.nest.com/reference/api-smoke-co-alarm) also seems pretty light on (as I’m sure you know). Do you know if have any access to extra doco if you have a developer account?

So I guess we’re a bit stuck. Have you got any other diagnostics with `component_heat_test_passed` yet?

> I will include that one to the redaction engine in an upcoming update. Makes sense, since this could also be used to identify a location.

That would be great, thanks! I probably redacted more than I needed, but was a bit disturbed by all the data I had given Google!

**Comment by iMicknl** [comment]
Thanks for your extensive research! I couldn't find any good references as well, and I don't have access to the (full) Nest API documentation. I wasn't aware of the doc you shared though, but it seems just for their old API. Currently we use an internal and undocumented API.

I think I will just remove this binary_sensor to avoid this confusion, and we can always add it back if there is a need.
