### ISSUE TITLE
"Unknown exception. Live updates disabled" in logs

### ISSUE THREAD

**Issue by Anto79-ops** [iMicknl/ha-nest-protect#71]
### The problem

Hey thanks for thing integration and for your work here! awesome!

wanted to also bring to your attention an error log message. Any idea what it means?

```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:220
Integration: Nest Protect (documentation, issues)
First occurred: 2:53:26 PM (1 occurrences)
Last logged: 2:53:26 PM

Unknown exception. Live updates disabled. Please turn on debug mode and create an issue on GitHub.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('34.198.123.254', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 126, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 220, in subscribe_for_data
    async with self.session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host czfe35-front01-iad01.transport.home.nest.com:443 ssl:default [Connect call failed ('34.198.123.254', 443)]
```

### What version of this integration (ha-nest-protect) has the issue?

latest for today

### What version of Home Assistant Core has the issue?

core-2022.4.2

### Device / Model

Nest Protect Battery

### Diagnostics information

just noticed it in logs

### Home Assistant log

<details><summary>Logs</summary>
```
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:220
Integration: Nest Protect (documentation, issues)
First occurred: 2:53:26 PM (1 occurrences)
Last logged: 2:53:26 PM

Unknown exception. Live updates disabled. Please turn on debug mode and create an issue on GitHub.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('34.198.123.254', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 126, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 220, in subscribe_for_data
    async with self.session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host czfe35-front01-iad01.transport.home.nest.com:443 ssl:default [Connect call failed ('34.198.123.254', 443)]
```

</details>

**Comment by iMicknl** [comment]
Thanks! It seems that you lost internet connection and that this integration is not yet handling that in a good way.

The reason why we disable updates and print `Unknown exception. Live updates disabled. Please turn on debug mode and create an issue on GitHub.` is to make sure we don't keep hammering the Nest server when something goes wrong.

**Comment by Anto79-ops** [comment]
ahhh that makes sense because it doesn't always show up in the logs. OK, thanks for explaining that! Cheers

**Comment by iMicknl** [comment]
@Anto79-ops I will fix it, however that probably will take a few weeks. :-)

**Comment by operinko** [comment]
```
2022-04-17 13:18:42 DEBUG (MainThread) [custom_components.nest_protect] Subscriber: listening for new data
2022-04-17 13:18:43 ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Live updates disabled. Please turn on debug mode and create an issue on GitHub.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 134, in _async_subscribe_for_data
for bucket in result["objects"]:
KeyError: 'objects'
```

Debug mode is enabled with, and that's all I'm seeing:
```
logger:
  default: critical
  logs:
    custom_components.nest_protect: debug
```

**Comment by iMicknl** [comment]
@operinko could you perhaps see if this happens more often? Otherwise please create a new issue with more information.
