### ISSUE TITLE
Inknown exception ?

### ISSUE THREAD

**Issue by stefanuytterhoeven** [iMicknl/ha-nest-protect#80]
### The problem

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:177
Integration: Nest Protect (documentation, issues)
First occurred: 05:31:41 (1 occurrences)
Last logged: 05:31:41

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 141, in _async_subscribe_for_data
    await entry_data.client.authenticate(entry_data.client.auth.access_token)
  File "/config/custom_components/nest_protect/pynest/client.py", line 177, in authenticate
    nest_response = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://home.nest.com/session')

### What version of this integration (ha-nest-protect) has the issue?

v0.3.6

### What version of Home Assistant Core has the issue?

2022.5.0

### Device / Model

Nest Protect (Battery)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Thanks @stefanuytterhoeven! I will have a look if I can improve the logging to figure out the source of this issue. Nest returns something that we don't expect, but in this case the response is not correctly logged...

**Comment by stefanuytterhoeven** [comment]
Fyi:
I have three battery powered nest protects

**Comment by olafvs** [comment]
Hi, I'm on 0.3.7 with more logging and also get this error.

`2022-05-20 01:27:24 ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
File "/config/custom_components/nest_protect/pynest/client.py", line 259, in subscribe_for_data
result = await response.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe34-front01-iad01.transport.home.nest.com/v6/subscribe')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/nest_protect/__init__.py", line 144, in _async_subscribe_for_data
result = await entry_data.client.subscribe_for_data(
File "/config/custom_components/nest_protect/pynest/client.py", line 263, in subscribe_for_data
raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 400 error while subscribing -`

**Comment by craibo** [comment]
Good day @iMicknl 

I have also started seeing the `Unknown pynest exception` error this morning 

`
This error originated from a custom integration.

Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:263
Integration: Nest Protect (documentation, issues)
First occurred: 08:21:42 (1 occurrences)
Last logged: 08:21:42

Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/pynest/client.py", line 259, in subscribe_for_data
    result = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url=URL('https://czfe74-front01-iad01.transport.home.nest.com/v6/subscribe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 144, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 263, in subscribe_for_data
    raise PynestException(
custom_components.nest_protect.pynest.exceptions.PynestException: 200 error while subscribing - 
`

**Comment by iMicknl** [comment]
@craibo which version do you run?
