### ISSUE TITLE
ClientOSError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by jprokopowich** [iMicknl/ha-nest-protect#99]
### The problem

This error originated from a custom integration.
```
Logger: custom_components.nest_protect
Source: custom_components/nest_protect/pynest/client.py:242
Integration: Nest Protect (documentation, issues)
First occurred: 6:41:53 AM (1 occurrences)
Last logged: 6:41:53 AM

Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
Traceback (most recent call last):
  File "/config/custom_components/nest_protect/__init__.py", line 144, in _async_subscribe_for_data
    result = await entry_data.client.subscribe_for_data(
  File "/config/custom_components/nest_protect/pynest/client.py", line 242, in subscribe_for_data
    async with self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

### What version of this integration (ha-nest-protect) has the issue?

v0.3.8

### What version of Home Assistant Core has the issue?

2022.8.7

### Device / Model

Nest Protect wired

### Diagnostics information

[nest_protect-35892183b4b12d5b93434ae1d74a1b83-Nest Protect (room)-6befb339d901031fa0f94e3cf79e03cc.json.txt](https://github.com/iMicknl/ha-nest-protect/files/9542431/nest_protect-35892183b4b12d5b93434ae1d74a1b83-Nest.Protect.room.-6befb339d901031fa0f94e3cf79e03cc.json.txt)

### Home Assistant log

<details><summary>Logs</summary>
```
Copy/paste any log here, between the starting and ending backticks (`)
```

</details>

**Comment by iMicknl** [comment]
Do you still face this issue? I will see if we can add retry logic to the integration.

**Comment by jprokopowich** [comment]
I don't remember seeing it for a while now.
